using ApplicationCore.Enums;

namespace ApplicationCore.Entities.InitialData;

public static class TelescopesInitData
{
    public static readonly Telescope[] Data =
    {
        new Telescope
        {
            Id = Guid.Parse("9b9fbff4-3a3a-4a71-b1d7-8a09872919d7"),
            Aperture = 50,
            ApertureRatio = 1,
            EyepieceFittingDiameter = 1,
            FocusDistance = 600,
            MaxUsefulScale = 100,
            MinUsefulScale = 1,
            MountingType = MountingType.Azimutal,
            TelescopeControlType = TelescopeControlType.Manual,
            ScaleMax = 1,
            ScaleMin = 1,
            Seeker = "",
            TripodHeight = "",
            TripodMaterial = "",
            Type = TelescopeType.Refractor,
            TelescopeUserLevel = TelescopeUserLevel.ForBeginners,
            Weight = 20,
            ProductId = Guid.Parse("26e52bab-4c7e-4f92-b46e-8708b1e4f302"),
            CreatedAt = new DateTime(2023, 01, 01, 0, 0, 0, DateTimeKind.Utc),
        },
        new Telescope
        {
            Id = Guid.Parse("9b9fbff4-3a3a-4a71-b1d7-1a69872919d7"),
            Aperture = 150,
            ApertureRatio = 9.3m,
            EyepieceFittingDiameter = 1.25m,
            FocusDistance = 1400,
            MaxUsefulScale = 1050,
            MinUsefulScale = 70,
            MountingType = MountingType.Equatorial,
            TelescopeControlType = TelescopeControlType.Manual,
            ScaleMax = 70,
            ScaleMin = 1050,
            Seeker = "с красной точкой",
            TripodHeight = "",
            TripodMaterial = "стальная",
            Type = TelescopeType.Reflector,
            TelescopeUserLevel = TelescopeUserLevel.ForConfidentUsers,
            Weight = null,
            ProductId = Guid.Parse("26e52bab-4c7e-4f92-b46e-8708b1936302"),
            CreatedAt = new DateTime(2023, 01, 03, 0, 0, 0, DateTimeKind.Utc),
        },
        
        new Telescope
        {
            Id = Guid.Parse("76d45a33-1852-4f7a-8ec5-0ff472db6b1d"),
            Aperture = 114,
            ApertureRatio = 8.0m,
            EyepieceFittingDiameter = 1.25m,
            FocusDistance = 900,
            MaxUsefulScale = 228,
            MinUsefulScale = null,
            MountingType = MountingType.EquatorialEQ1,
            TelescopeControlType = TelescopeControlType.Manual,
            ScaleMax = 228,
            ScaleMin = null,
            Seeker = "6x24, оптический",
            TripodHeight = "650–1200",
            TripodMaterial = "алюминиевая",
            Type = TelescopeType.Reflector,
            TelescopeUserLevel = TelescopeUserLevel.ForBeginners,
            Weight = null,
            ProductId = Guid.Parse("9dd4a5ef-bb70-4acd-8c3b-1f5942bedcd0"),
            CreatedAt = new DateTime(2023, 01, 04, 0, 0, 0, DateTimeKind.Utc),
        },
        new Telescope
        {
            Id = Guid.Parse("ac88f3e7-4983-45be-9974-a05b0946975f"),
            Aperture = 203,
            ApertureRatio = 4m,
            EyepieceFittingDiameter = 1.25m,
            FocusDistance = 800,
            MaxUsefulScale = 406,
            MinUsefulScale = null,
            MountingType = MountingType.Equatorial,
            TelescopeControlType = TelescopeControlType.Manual,
            ScaleMax = 406,
            ScaleMin = null,
            Seeker = "8x50, оптический",
            TripodHeight = "нет",
            TripodMaterial = "нет",
            Type = TelescopeType.Reflector,
            TelescopeUserLevel = TelescopeUserLevel.ForConfidentUsers,
            Weight = 15,
            ProductId = Guid.Parse("bb3de5c0-daa1-4b80-8a01-6558005db3c5"),
            CreatedAt = new DateTime(2023, 01, 05, 0, 0, 0, DateTimeKind.Utc),
        },
        new Telescope
        {
            Id = Guid.Parse("3e8c66c1-5f34-4550-b3aa-39a4f50a975a"),
            Aperture = 130,
            ApertureRatio = 4m,
            EyepieceFittingDiameter = 1.25m,
            FocusDistance = 900,
            MaxUsefulScale = 260,
            MinUsefulScale = null,
            MountingType = MountingType.Equatorial,
            TelescopeControlType = TelescopeControlType.Manual,
            ScaleMax = 406,
            ScaleMin = null,
            Seeker = "8x50, оптический",
            TripodHeight = "нет",
            TripodMaterial = "нет",
            Type = TelescopeType.Reflector,
            TelescopeUserLevel = TelescopeUserLevel.ForBeginners,
            Weight = 15,
            ProductId = Guid.Parse("f6112b01-2549-4a80-98a8-8bb1eaeca160"),
            CreatedAt = new DateTime(2023, 01, 05, 0, 0, 0, DateTimeKind.Utc),
        },
    };
}