// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230515223207_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence<int>("SEQ_order_number")
                .StartsAt(10000L);

            modelBuilder.HasSequence<int>("SEQ_paperwork_order_number");

            modelBuilder.HasSequence<int>("SEQ_reserve_request_number")
                .StartsAt(10000L);

            modelBuilder.Entity("ApplicationCore.Entities.Accessory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessoryType")
                        .HasColumnType("integer")
                        .HasColumnName("accessory_type");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.HasKey("Id")
                        .HasName("pk_accessory");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_accessory_product_id");

                    b.ToTable("accessory", (string)null);
                });

            modelBuilder.Entity("ApplicationCore.Entities.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Building")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("building");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<string>("Flat")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("flat");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("postal_code");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("street");

                    b.HasKey("Id")
                        .HasName("pk_address");

                    b.ToTable("address", (string)null);
                });

            modelBuilder.Entity("ApplicationCore.Entities.Assignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AffiliateNumber")
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("affiliate_number");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("phone");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid?>("UserId1")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id1");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_assignment");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_assignment_created_by_user_id");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_assignment_role_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_assignment_user_id");

                    b.HasIndex("UserId1")
                        .IsUnique()
                        .HasDatabaseName("ix_assignment_user_id1");

                    b.ToTable("assignment", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("348a8f47-a4f5-4ac0-8c3c-282c6b03118d"),
                            CreatedAt = new DateTime(2020, 11, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("8faeffed-e97c-4262-9bb9-995f558e6c8c"),
                            Phone = "+11",
                            RoleId = new Guid("a8aecf8e-1dba-497f-abdd-74db9384398e"),
                            Status = 1,
                            UserId = new Guid("8faeffed-e97c-4262-9bb9-995f558e6c8c"),
                            Version = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("ApplicationCore.Entities.Binocular", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Aperture")
                        .HasColumnType("numeric")
                        .HasColumnName("aperture");

                    b.Property<decimal>("ExitPupilDiameterMax")
                        .HasColumnType("numeric")
                        .HasColumnName("exit_pupil_diameter_max");

                    b.Property<decimal>("ExitPupilDiameterMin")
                        .HasColumnType("numeric")
                        .HasColumnName("exit_pupil_diameter_min");

                    b.Property<decimal>("FocusDistanceMin")
                        .HasColumnType("numeric")
                        .HasColumnName("focus_distance_min");

                    b.Property<int>("FocusingMethod")
                        .HasColumnType("integer")
                        .HasColumnName("focusing_method");

                    b.Property<decimal>("FovMax")
                        .HasColumnType("numeric")
                        .HasColumnName("fov_max");

                    b.Property<decimal>("FovMin")
                        .HasColumnType("numeric")
                        .HasColumnName("fov_min");

                    b.Property<decimal>("HasAdapter")
                        .HasColumnType("numeric")
                        .HasColumnName("has_adapter");

                    b.Property<decimal>("HasCase")
                        .HasColumnType("numeric")
                        .HasColumnName("has_case");

                    b.Property<decimal>("HasMoistureProtection")
                        .HasColumnType("numeric")
                        .HasColumnName("has_moisture_protection");

                    b.Property<decimal>("InterpupillaryDistanseMax")
                        .HasColumnType("numeric")
                        .HasColumnName("interpupillary_distanse_max");

                    b.Property<decimal>("InterpupillaryDistanseMin")
                        .HasColumnType("numeric")
                        .HasColumnName("interpupillary_distanse_min");

                    b.Property<int>("OpticsMaterial")
                        .HasColumnType("integer")
                        .HasColumnName("optics_material");

                    b.Property<int>("PrismType")
                        .HasColumnType("integer")
                        .HasColumnName("prism_type");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<int>("Purpose")
                        .HasColumnType("integer")
                        .HasColumnName("purpose");

                    b.Property<decimal>("RelativeBrightnessMax")
                        .HasColumnType("numeric")
                        .HasColumnName("relative_brightness_max");

                    b.Property<decimal>("RelativeBrightnessMin")
                        .HasColumnType("numeric")
                        .HasColumnName("relative_brightness_min");

                    b.Property<decimal>("RemovalExitPupilMax")
                        .HasColumnType("numeric")
                        .HasColumnName("removal_exit_pupil_max");

                    b.Property<decimal>("RemovalExitPupilMin")
                        .HasColumnType("numeric")
                        .HasColumnName("removal_exit_pupil_min");

                    b.Property<decimal>("ScaleMax")
                        .HasColumnType("numeric")
                        .HasColumnName("scale_max");

                    b.Property<decimal>("ScaleMin")
                        .HasColumnType("numeric")
                        .HasColumnName("scale_min");

                    b.Property<int>("Size")
                        .HasColumnType("integer")
                        .HasColumnName("size");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("pk_binocular");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_binocular_product_id");

                    b.ToTable("binocular", (string)null);
                });

            modelBuilder.Entity("ApplicationCore.Entities.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CategoryType")
                        .HasColumnType("integer")
                        .HasColumnName("category_type");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_brand");

                    b.ToTable("brand", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("445faffb-0213-42f4-ab19-a22834ec3cb6"),
                            CategoryType = 1,
                            Code = "1",
                            Name = "Levenhuk"
                        },
                        new
                        {
                            Id = new Guid("5bfaa88a-8b4c-4092-8c41-f9c2e3982ff1"),
                            CategoryType = 1,
                            Code = "2",
                            Name = "Bresser"
                        },
                        new
                        {
                            Id = new Guid("1a73828e-952c-488d-b5d9-25309e33b619"),
                            CategoryType = 1,
                            Code = "3",
                            Name = "Sky-Watcher"
                        },
                        new
                        {
                            Id = new Guid("bd947615-ca7d-4db1-a6ec-f685f8f25876"),
                            CategoryType = 2,
                            Code = "4",
                            Name = "Levenhuk"
                        },
                        new
                        {
                            Id = new Guid("7a5776d8-914b-4bf1-a0be-c61467ccd3f6"),
                            CategoryType = 2,
                            Code = "5",
                            Name = "Bresser"
                        });
                });

            modelBuilder.Entity("ApplicationCore.Entities.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CustomerAssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_assignment_id");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("total_amount");

                    b.HasKey("Id")
                        .HasName("pk_cart");

                    b.HasIndex("CustomerAssignmentId")
                        .HasDatabaseName("ix_cart_customer_assignment_id");

                    b.ToTable("cart", (string)null);
                });

            modelBuilder.Entity("ApplicationCore.Entities.CartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CartId")
                        .HasColumnType("uuid")
                        .HasColumnName("cart_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.HasKey("Id")
                        .HasName("pk_cart_item");

                    b.HasIndex("CartId")
                        .HasDatabaseName("ix_cart_item_cart_id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_cart_item_product_id");

                    b.ToTable("cart_item", (string)null);
                });

            modelBuilder.Entity("ApplicationCore.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("ProductsCount")
                        .HasColumnType("integer")
                        .HasColumnName("products_count");

                    b.HasKey("Id")
                        .HasName("pk_category");

                    b.ToTable("category", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("df445d42-ca49-4fc5-9573-a14371daf34b"),
                            Code = "1",
                            Description = "Telescopes",
                            Name = "Telescopes",
                            ProductsCount = 0
                        },
                        new
                        {
                            Id = new Guid("e3e6c141-8d10-49fb-8f60-a0393425d025"),
                            Code = "2",
                            Description = "Binoculars",
                            Name = "Binoculars",
                            ProductsCount = 0
                        },
                        new
                        {
                            Id = new Guid("6140552f-af4c-4d2b-8c35-41d764eb1ba3"),
                            Code = "3",
                            Description = "Accessories",
                            Name = "Accessories",
                            ProductsCount = 0
                        });
                });

            modelBuilder.Entity("ApplicationCore.Entities.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignment_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_comment");

                    b.HasIndex("AssignmentId")
                        .HasDatabaseName("ix_comment_assignment_id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_comment_product_id");

                    b.ToTable("comment", (string)null);
                });

            modelBuilder.Entity("ApplicationCore.Entities.Currency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("abbreviation");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_currency");

                    b.ToTable("currency", (string)null);
                });

            modelBuilder.Entity("ApplicationCore.Entities.CurrencyExchange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("FromCurrencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_currency_id");

                    b.Property<float>("Ratio")
                        .HasColumnType("real")
                        .HasColumnName("ratio");

                    b.Property<Guid>("ToCurrencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_currency_id");

                    b.HasKey("Id")
                        .HasName("pk_currency_exchange");

                    b.HasIndex("FromCurrencyId")
                        .HasDatabaseName("ix_currency_exchange_from_currency_id");

                    b.HasIndex("ToCurrencyId")
                        .HasDatabaseName("ix_currency_exchange_to_currency_id");

                    b.ToTable("currency_exchange", (string)null);
                });

            modelBuilder.Entity("ApplicationCore.Entities.File", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssignmentId")
                        .IsRequired()
                        .HasColumnType("uuid")
                        .HasColumnName("assignment_id");

                    b.Property<int>("AttachmentType")
                        .HasColumnType("integer")
                        .HasColumnName("attachment_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("extension");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<long>("FileSizeInBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size_in_bytes");

                    b.Property<bool>("IsAttached")
                        .HasColumnType("boolean")
                        .HasColumnName("is_attached");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("mime_type");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("reference");

                    b.Property<int>("StorageType")
                        .HasColumnType("integer")
                        .HasColumnName("storage_type");

                    b.HasKey("Id")
                        .HasName("pk_file");

                    b.HasIndex("AssignmentId")
                        .HasDatabaseName("ix_file_assignment_id");

                    b.ToTable("file", (string)null);
                });

            modelBuilder.Entity("ApplicationCore.Entities.LegalDetails", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bank_name");

                    b.Property<string>("Bic")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bic");

                    b.Property<string>("Iban")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("iban");

                    b.Property<Guid>("LegalAddressId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_address_id");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("legal_name");

                    b.Property<string>("Unp")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unp");

                    b.HasKey("Id")
                        .HasName("pk_legal_details");

                    b.HasIndex("LegalAddressId")
                        .HasDatabaseName("ix_legal_details_legal_address_id");

                    b.ToTable("legal_details", (string)null);
                });

            modelBuilder.Entity("ApplicationCore.Entities.ObjectForObservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_object_for_observation");

                    b.ToTable("object_for_observation", (string)null);
                });

            modelBuilder.Entity("ApplicationCore.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ConsumerAssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("consumer_assignment_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ManagerAssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("manager_assignment_id");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<int>("OrderNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("order_number")
                        .HasDefaultValueSql("nextval('\"SEQ_order_number\"')");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("integer")
                        .HasColumnName("order_status");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("integer")
                        .HasColumnName("payment_method");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("total_amount");

                    b.HasKey("Id")
                        .HasName("pk_order");

                    b.HasIndex("ConsumerAssignmentId")
                        .HasDatabaseName("ix_order_consumer_assignment_id");

                    b.HasIndex("ManagerAssignmentId")
                        .HasDatabaseName("ix_order_manager_assignment_id");

                    b.ToTable("order", (string)null);
                });

            modelBuilder.Entity("ApplicationCore.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("pk_order_item");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_order_item_order_id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_order_item_product_id");

                    b.ToTable("order_item", (string)null);
                });

            modelBuilder.Entity("ApplicationCore.Entities.OrderItemProductItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("OrderItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_item_id");

                    b.Property<Guid>("ProductItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_item_id");

                    b.HasKey("Id")
                        .HasName("pk_order_item_product_item");

                    b.HasIndex("OrderItemId")
                        .HasDatabaseName("ix_order_item_product_item_order_item_id");

                    b.HasIndex("ProductItemId")
                        .HasDatabaseName("ix_order_item_product_item_product_item_id");

                    b.ToTable("order_item_product_item", (string)null);
                });

            modelBuilder.Entity("ApplicationCore.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<Guid>("ConsumerAssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("consumer_assignment_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("integer")
                        .HasColumnName("payment_status");

                    b.Property<int>("PaymentType")
                        .HasColumnType("integer")
                        .HasColumnName("payment_type");

                    b.HasKey("Id")
                        .HasName("pk_payment");

                    b.HasIndex("ConsumerAssignmentId")
                        .HasDatabaseName("ix_payment_consumer_assignment_id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_payment_order_id");

                    b.ToTable("payment", (string)null);
                });

            modelBuilder.Entity("ApplicationCore.Entities.PersonalData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AddressId")
                        .HasColumnType("uuid")
                        .HasColumnName("address_id");

                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignment_id");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("birthday");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("gender");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<Guid>("LegalDetailsId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_details_id");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.HasKey("Id")
                        .HasName("pk_personal_data");

                    b.HasIndex("AddressId")
                        .HasDatabaseName("ix_personal_data_address_id");

                    b.HasIndex("AssignmentId")
                        .HasDatabaseName("ix_personal_data_assignment_id");

                    b.HasIndex("LegalDetailsId")
                        .HasDatabaseName("ix_personal_data_legal_details_id");

                    b.ToTable("personal_data", (string)null);
                });

            modelBuilder.Entity("ApplicationCore.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uuid")
                        .HasColumnName("brand_id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Equipment")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("equipment");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("manufacturer");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("short_description");

                    b.Property<string>("SpecialNote")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("special_note");

                    b.HasKey("Id")
                        .HasName("pk_product");

                    b.HasIndex("BrandId")
                        .HasDatabaseName("ix_product_brand_id");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_product_category_id");

                    b.HasIndex("Code")
                        .HasDatabaseName("ix_product_code");

                    b.ToTable("product", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("26e52bab-4c7e-4f92-b46e-8708b1e4f302"),
                            BrandId = new Guid("445faffb-0213-42f4-ab19-a22834ec3cb6"),
                            CategoryId = new Guid("df445d42-ca49-4fc5-9573-a14371daf34b"),
                            Code = "T1",
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Телескоп Levenhuk Skyline Travel Sun 70 – компактный рефрактор для прогулок и путешествий. Длина его трубы составляет всего 40 см при апертуре 70 мм. В комплект входит удобный фирменный рюкзак, в него легко поместятся телескоп, монтировка, тренога и все необходимые аксессуары. Оптический прибор подойдет для наблюдения планет и спутников, а также деталей ландшафта и архитектуры. В идеальных условиях в него можно рассмотреть большинство объектов из каталога Мессье (без деталей), щель Кассини, кольца Сатурна и Большое Красное Пятно на Юпитере.",
                            Equipment = "",
                            Manufacturer = "КНР for Levenhuk, Inc. (USA)",
                            ModifiedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Телескоп Levenhuk Skyline Travel Sun 70",
                            Price = 703.60m,
                            Quantity = 20,
                            ShortDescription = "компактный рефрактор для прогулок и путешествий.",
                            SpecialNote = ""
                        });
                });

            modelBuilder.Entity("ApplicationCore.Entities.ProductItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsSold")
                        .HasColumnType("boolean")
                        .HasColumnName("is_sold");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("serial_number");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sku");

                    b.HasKey("Id")
                        .HasName("pk_product_item");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_product_item_product_id");

                    b.HasIndex("SerialNumber")
                        .HasDatabaseName("ix_product_item_serial_number");

                    b.HasIndex("Sku")
                        .HasDatabaseName("ix_product_item_sku");

                    b.ToTable("product_item", (string)null);
                });

            modelBuilder.Entity("ApplicationCore.Entities.Promotion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsSpecial")
                        .HasColumnType("boolean")
                        .HasColumnName("is_special");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PromoCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("promo_code");

                    b.Property<decimal>("PromoRate")
                        .HasColumnType("numeric")
                        .HasColumnName("promo_rate");

                    b.Property<int>("PromotionType")
                        .HasColumnType("integer")
                        .HasColumnName("promotion_type");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_promotion");

                    b.HasIndex("PromoCode")
                        .HasDatabaseName("ix_promotion_promo_code");

                    b.ToTable("promotion", (string)null);
                });

            modelBuilder.Entity("ApplicationCore.Entities.PromotionProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<Guid>("PromotionId")
                        .HasColumnType("uuid")
                        .HasColumnName("promotion_id");

                    b.HasKey("Id")
                        .HasName("pk_promotion_product");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_promotion_product_product_id");

                    b.HasIndex("PromotionId")
                        .HasDatabaseName("ix_promotion_product_promotion_id");

                    b.ToTable("promotion_product", (string)null);
                });

            modelBuilder.Entity("ApplicationCore.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_role");

                    b.ToTable("role", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("04e7d93f-8c78-47cb-a56f-6244a0a0fc56"),
                            Name = "Staff"
                        },
                        new
                        {
                            Id = new Guid("55e1b1f5-0a7b-49c1-8d61-5a20e93111dd"),
                            Name = "Manager"
                        },
                        new
                        {
                            Id = new Guid("cd7be9d2-7898-4673-8698-672d07594ec8"),
                            Name = "Consumer"
                        },
                        new
                        {
                            Id = new Guid("a8aecf8e-1dba-497f-abdd-74db9384398e"),
                            Name = "System"
                        });
                });

            modelBuilder.Entity("ApplicationCore.Entities.SecretToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsAttached")
                        .HasColumnType("boolean")
                        .HasColumnName("is_attached");

                    b.HasKey("Id")
                        .HasName("pk_secret_token");

                    b.ToTable("secret_token", (string)null);
                });

            modelBuilder.Entity("ApplicationCore.Entities.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssignmentId")
                        .IsRequired()
                        .HasColumnType("uuid")
                        .HasColumnName("assignment_id");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_date");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiry_date");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("fingerprint");

                    b.Property<bool>("Invalidated")
                        .HasColumnType("boolean")
                        .HasColumnName("invalidated");

                    b.Property<Guid?>("OriginAssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("origin_assignment_id");

                    b.Property<Guid>("RefreshToken")
                        .HasColumnType("uuid")
                        .HasColumnName("refresh_token");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_session");

                    b.HasIndex("AssignmentId")
                        .HasDatabaseName("ix_session_assignment_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_session_user_id");

                    b.ToTable("session", (string)null);
                });

            modelBuilder.Entity("ApplicationCore.Entities.SetupPasswordHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_setup_password_history");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_setup_password_history_user_id");

                    b.ToTable("setup_password_history", (string)null);
                });

            modelBuilder.Entity("ApplicationCore.Entities.SetupPasswordToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiry_date");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_used");

                    b.Property<string>("TokenValue")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("token_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_setup_password_token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_setup_password_token_user_id");

                    b.ToTable("setup_password_token", (string)null);
                });

            modelBuilder.Entity("ApplicationCore.Entities.SoldProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("total_amount");

                    b.HasKey("Id")
                        .HasName("pk_sold_product");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_sold_product_product_id");

                    b.ToTable("sold_product", (string)null);
                });

            modelBuilder.Entity("ApplicationCore.Entities.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AffiliateNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("affiliate_number");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<Guid>("LegalDetailsId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_details_id");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("product_code");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("short_name");

                    b.HasKey("Id")
                        .HasName("pk_supplier");

                    b.HasIndex("LegalDetailsId")
                        .HasDatabaseName("ix_supplier_legal_details_id");

                    b.ToTable("supplier", (string)null);
                });

            modelBuilder.Entity("ApplicationCore.Entities.Telescope", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Aperture")
                        .HasColumnType("numeric")
                        .HasColumnName("aperture");

                    b.Property<decimal>("ApertureRatio")
                        .HasColumnType("numeric")
                        .HasColumnName("aperture_ratio");

                    b.Property<decimal>("EyepieceFittingDiameter")
                        .HasColumnType("numeric")
                        .HasColumnName("eyepiece_fitting_diameter");

                    b.Property<decimal>("FocusDistance")
                        .HasColumnType("numeric")
                        .HasColumnName("focus_distance");

                    b.Property<decimal>("MaxUsefulScale")
                        .HasColumnType("numeric")
                        .HasColumnName("max_useful_scale");

                    b.Property<decimal>("MinUsefulScale")
                        .HasColumnType("numeric")
                        .HasColumnName("min_useful_scale");

                    b.Property<int>("MountingType")
                        .HasColumnType("integer")
                        .HasColumnName("mounting_type");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<decimal>("ScaleMax")
                        .HasColumnType("numeric")
                        .HasColumnName("scale_max");

                    b.Property<decimal>("ScaleMin")
                        .HasColumnType("numeric")
                        .HasColumnName("scale_min");

                    b.Property<string>("Seeker")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("seeker");

                    b.Property<int>("TelescopeControlType")
                        .HasColumnType("integer")
                        .HasColumnName("telescope_control_type");

                    b.Property<int>("TelescopeUserLevel")
                        .HasColumnType("integer")
                        .HasColumnName("telescope_user_level");

                    b.Property<string>("TripodHeight")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tripod_height");

                    b.Property<string>("TripodMaterial")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tripod_material");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("pk_telescope");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_telescope_product_id");

                    b.ToTable("telescope", (string)null);
                });

            modelBuilder.Entity("ApplicationCore.Entities.TelescopeEyepiece", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("EffectiveScale")
                        .HasColumnType("numeric")
                        .HasColumnName("effective_scale");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("TelescopeId")
                        .HasColumnType("uuid")
                        .HasColumnName("telescope_id");

                    b.HasKey("Id")
                        .HasName("pk_telescope_eyepiece");

                    b.HasIndex("TelescopeId")
                        .HasDatabaseName("ix_telescope_eyepiece_telescope_id");

                    b.ToTable("telescope_eyepiece", (string)null);
                });

            modelBuilder.Entity("ApplicationCore.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("citext")
                        .HasColumnName("email");

                    b.Property<DateTime?>("FirstLoginDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_login_date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("last_name");

                    b.Property<DateTime?>("LockedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_at");

                    b.Property<DateTime?>("PasswordChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("password_changed_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("WrongPasswordLogInAttemptsCount")
                        .HasColumnType("integer")
                        .HasColumnName("wrong_password_log_in_attempts_count");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_user_created_by_user_id");

                    b.HasIndex("Email")
                        .HasDatabaseName("ix_user_email");

                    b.HasIndex("FirstName")
                        .HasDatabaseName("ix_user_first_name");

                    b.HasIndex("LastName")
                        .HasDatabaseName("ix_user_last_name");

                    b.ToTable("user", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8faeffed-e97c-4262-9bb9-995f558e6c8c"),
                            CreatedAt = new DateTime(2020, 11, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("8faeffed-e97c-4262-9bb9-995f558e6c8c"),
                            Email = "systemEmail",
                            FirstName = "System",
                            LastName = "",
                            PasswordHash = "",
                            WrongPasswordLogInAttemptsCount = 0
                        });
                });

            modelBuilder.Entity("Infrastructure.Entities.JwtKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_from");

                    b.Property<Guid>("SecretId")
                        .HasColumnType("uuid")
                        .HasColumnName("secret_id");

                    b.Property<DateTime>("SigningEffectiveTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("signing_effective_to");

                    b.Property<DateTime>("ValidationEffectiveTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("validation_effective_to");

                    b.HasKey("Id")
                        .HasName("pk_jwt_key");

                    b.HasIndex("SecretId")
                        .IsUnique()
                        .HasDatabaseName("ix_jwt_key_secret_id");

                    b.ToTable("jwt_key", (string)null);
                });

            modelBuilder.Entity("ApplicationCore.Entities.Accessory", b =>
                {
                    b.HasOne("ApplicationCore.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_accessory_product_product_id");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ApplicationCore.Entities.Assignment", b =>
                {
                    b.HasOne("ApplicationCore.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_assignment_user_created_by_user_id");

                    b.HasOne("ApplicationCore.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_assignment_role_role_id");

                    b.HasOne("ApplicationCore.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_assignment_user_user_id");

                    b.HasOne("ApplicationCore.Entities.User", null)
                        .WithOne("Assignment")
                        .HasForeignKey("ApplicationCore.Entities.Assignment", "UserId1")
                        .HasConstraintName("fk_assignment_user_user_id1");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ApplicationCore.Entities.Binocular", b =>
                {
                    b.HasOne("ApplicationCore.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_binocular_product_product_id");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ApplicationCore.Entities.Cart", b =>
                {
                    b.HasOne("ApplicationCore.Entities.Assignment", "CustomerAssignment")
                        .WithMany()
                        .HasForeignKey("CustomerAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cart_assignment_customer_assignment_id");

                    b.Navigation("CustomerAssignment");
                });

            modelBuilder.Entity("ApplicationCore.Entities.CartItem", b =>
                {
                    b.HasOne("ApplicationCore.Entities.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cart_item_cart_cart_id");

                    b.HasOne("ApplicationCore.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cart_item_product_product_id");

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ApplicationCore.Entities.Comment", b =>
                {
                    b.HasOne("ApplicationCore.Entities.Assignment", "Assignment")
                        .WithMany()
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comment_assignment_assignment_id");

                    b.HasOne("ApplicationCore.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comment_product_product_id");

                    b.Navigation("Assignment");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ApplicationCore.Entities.CurrencyExchange", b =>
                {
                    b.HasOne("ApplicationCore.Entities.Currency", "FromCurrency")
                        .WithMany()
                        .HasForeignKey("FromCurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_currency_exchange_currency_from_currency_id");

                    b.HasOne("ApplicationCore.Entities.Currency", "ToCurrency")
                        .WithMany()
                        .HasForeignKey("ToCurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_currency_exchange_currency_to_currency_id");

                    b.Navigation("FromCurrency");

                    b.Navigation("ToCurrency");
                });

            modelBuilder.Entity("ApplicationCore.Entities.File", b =>
                {
                    b.HasOne("ApplicationCore.Entities.Assignment", "Assignment")
                        .WithMany("AvatarFiles")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_file_assignment_assignment_id");

                    b.Navigation("Assignment");
                });

            modelBuilder.Entity("ApplicationCore.Entities.LegalDetails", b =>
                {
                    b.HasOne("ApplicationCore.Entities.Address", "LegalAddress")
                        .WithMany()
                        .HasForeignKey("LegalAddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_legal_details_address_legal_address_id");

                    b.Navigation("LegalAddress");
                });

            modelBuilder.Entity("ApplicationCore.Entities.Order", b =>
                {
                    b.HasOne("ApplicationCore.Entities.Assignment", "ConsumerAssignment")
                        .WithMany()
                        .HasForeignKey("ConsumerAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_assignment_consumer_assignment_id");

                    b.HasOne("ApplicationCore.Entities.Assignment", "ManagerAssignment")
                        .WithMany()
                        .HasForeignKey("ManagerAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_assignment_manager_assignment_id");

                    b.Navigation("ConsumerAssignment");

                    b.Navigation("ManagerAssignment");
                });

            modelBuilder.Entity("ApplicationCore.Entities.OrderItem", b =>
                {
                    b.HasOne("ApplicationCore.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_item_order_order_id");

                    b.HasOne("ApplicationCore.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_item_product_product_id");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ApplicationCore.Entities.OrderItemProductItem", b =>
                {
                    b.HasOne("ApplicationCore.Entities.OrderItem", "OrderItem")
                        .WithMany("ProductItems")
                        .HasForeignKey("OrderItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_item_product_item_order_item_order_item_id");

                    b.HasOne("ApplicationCore.Entities.ProductItem", "ProductItem")
                        .WithMany()
                        .HasForeignKey("ProductItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_item_product_item_product_item_product_item_id");

                    b.Navigation("OrderItem");

                    b.Navigation("ProductItem");
                });

            modelBuilder.Entity("ApplicationCore.Entities.Payment", b =>
                {
                    b.HasOne("ApplicationCore.Entities.Assignment", "ConsumerAssignment")
                        .WithMany()
                        .HasForeignKey("ConsumerAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_payment_assignment_consumer_assignment_id");

                    b.HasOne("ApplicationCore.Entities.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_payment_order_order_id");

                    b.Navigation("ConsumerAssignment");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("ApplicationCore.Entities.PersonalData", b =>
                {
                    b.HasOne("ApplicationCore.Entities.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_personal_data_address_address_id");

                    b.HasOne("ApplicationCore.Entities.Assignment", "Assignment")
                        .WithMany()
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_personal_data_assignment_assignment_id");

                    b.HasOne("ApplicationCore.Entities.LegalDetails", "LegalDetails")
                        .WithMany()
                        .HasForeignKey("LegalDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_personal_data_legal_details_legal_details_id");

                    b.Navigation("Address");

                    b.Navigation("Assignment");

                    b.Navigation("LegalDetails");
                });

            modelBuilder.Entity("ApplicationCore.Entities.Product", b =>
                {
                    b.HasOne("ApplicationCore.Entities.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_brand_brand_id");

                    b.HasOne("ApplicationCore.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_category_category_id");

                    b.Navigation("Brand");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ApplicationCore.Entities.ProductItem", b =>
                {
                    b.HasOne("ApplicationCore.Entities.Product", "Product")
                        .WithMany("ProductItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_item_product_product_id");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ApplicationCore.Entities.PromotionProduct", b =>
                {
                    b.HasOne("ApplicationCore.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_promotion_product_product_product_id");

                    b.HasOne("ApplicationCore.Entities.Promotion", "Promotion")
                        .WithMany("Products")
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_promotion_product_promotion_promotion_id");

                    b.Navigation("Product");

                    b.Navigation("Promotion");
                });

            modelBuilder.Entity("ApplicationCore.Entities.Session", b =>
                {
                    b.HasOne("ApplicationCore.Entities.Assignment", "Assignment")
                        .WithMany()
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_session_assignment_assignment_id");

                    b.HasOne("ApplicationCore.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_session_user_user_id");

                    b.Navigation("Assignment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ApplicationCore.Entities.SetupPasswordHistory", b =>
                {
                    b.HasOne("ApplicationCore.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_setup_password_history_user_user_id");
                });

            modelBuilder.Entity("ApplicationCore.Entities.SetupPasswordToken", b =>
                {
                    b.HasOne("ApplicationCore.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_setup_password_token_user_user_id");
                });

            modelBuilder.Entity("ApplicationCore.Entities.SoldProduct", b =>
                {
                    b.HasOne("ApplicationCore.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sold_product_product_product_id");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ApplicationCore.Entities.Supplier", b =>
                {
                    b.HasOne("ApplicationCore.Entities.LegalDetails", "LegalDetails")
                        .WithMany()
                        .HasForeignKey("LegalDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_supplier_legal_details_legal_details_id");

                    b.Navigation("LegalDetails");
                });

            modelBuilder.Entity("ApplicationCore.Entities.Telescope", b =>
                {
                    b.HasOne("ApplicationCore.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_telescope_product_product_id");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ApplicationCore.Entities.TelescopeEyepiece", b =>
                {
                    b.HasOne("ApplicationCore.Entities.Telescope", "Telescope")
                        .WithMany("TelescopeEyepieces")
                        .HasForeignKey("TelescopeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_telescope_eyepiece_telescope_telescope_id");

                    b.Navigation("Telescope");
                });

            modelBuilder.Entity("ApplicationCore.Entities.User", b =>
                {
                    b.HasOne("ApplicationCore.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_user_created_by_id");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("Infrastructure.Entities.JwtKey", b =>
                {
                    b.HasOne("ApplicationCore.Entities.SecretToken", "SecretToken")
                        .WithOne()
                        .HasForeignKey("Infrastructure.Entities.JwtKey", "SecretId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_jwt_key_secret_token_secret_token_id");

                    b.Navigation("SecretToken");
                });

            modelBuilder.Entity("ApplicationCore.Entities.Assignment", b =>
                {
                    b.Navigation("AvatarFiles");
                });

            modelBuilder.Entity("ApplicationCore.Entities.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("ApplicationCore.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("ApplicationCore.Entities.OrderItem", b =>
                {
                    b.Navigation("ProductItems");
                });

            modelBuilder.Entity("ApplicationCore.Entities.Product", b =>
                {
                    b.Navigation("ProductItems");
                });

            modelBuilder.Entity("ApplicationCore.Entities.Promotion", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ApplicationCore.Entities.Telescope", b =>
                {
                    b.Navigation("TelescopeEyepieces");
                });

            modelBuilder.Entity("ApplicationCore.Entities.User", b =>
                {
                    b.Navigation("Assignment")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
