// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Infrastructure.Migrations
{
    public partial class UpdateOrderInfo : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<Guid>(
                name: "address_id",
                table: "order",
                type: "uuid",
                nullable: true,
                defaultValue: null);

            migrationBuilder.AddColumn<string>(
                name: "customer_notes",
                table: "order",
                type: "text",
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<string>(
                name: "email",
                table: "order",
                type: "text",
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<string>(
                name: "first_name",
                table: "order",
                type: "text",
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<string>(
                name: "last_name",
                table: "order",
                type: "text",
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<string>(
                name: "phone_number",
                table: "order",
                type: "text",
                nullable: false,
                defaultValue: "");

            migrationBuilder.CreateIndex(
                name: "ix_order_address_id",
                table: "order",
                column: "address_id",
                unique: true);

            migrationBuilder.AddForeignKey(
                name: "fk_order_address_address_id",
                table: "order",
                column: "address_id",
                principalTable: "address",
                principalColumn: "id",
                onDelete: ReferentialAction.Cascade);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "fk_order_address_address_id",
                table: "order");

            migrationBuilder.DropIndex(
                name: "ix_order_address_id",
                table: "order");

            migrationBuilder.DropColumn(
                name: "address_id",
                table: "order");

            migrationBuilder.DropColumn(
                name: "customer_notes",
                table: "order");

            migrationBuilder.DropColumn(
                name: "email",
                table: "order");

            migrationBuilder.DropColumn(
                name: "first_name",
                table: "order");

            migrationBuilder.DropColumn(
                name: "last_name",
                table: "order");

            migrationBuilder.DropColumn(
                name: "phone_number",
                table: "order");
        }
    }
}
